export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const NO_AUTH = 'NO_AUTH';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const TWITTS_LIST_SAVE = 'TWITTS_LIST_SAVE';
export const TWITTS_ADD = 'TWITTS_ADD';
export const TWITTS_LOADING = 'TWITTS_LOADING';
export const TWITTS_ERROR = 'TWITTS_ERROR';
export const TWITTS_LIKE = 'TWITTS_LIKE';
export const TWITTS_COMMENT = 'TWITTS_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const TWITT_DELETE = 'TWITT_DELETE';
export const LOAD_TWITT = 'LOAD_TWITT';

export const ASYNC_TASK_START = 'ASYNC_TASK_START';

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
export const NOTIFICATION_LOADING = 'NOTIFICATION_LOADING';
export const MARK_ALLREAD_NOTIFICATION = 'MARK_ALLREAD_NOTIFICATION';
